postprocessor:
  name: fold_react
  APS_mode: True
  postprocessor_args:
    percentile: 90
    alpha: 0.1
    norm: false              # score normalization on/off
  postprocessor_sweep:
    percentile_list: [85, 90, 95, 99]
    alpha_list: [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0]  # overridden per dataset in the postprocessor
    norm_list: [false, true]
