postprocessor:
  name: fold
  APS_mode: True
  postprocessor_args:
    alpha: 0.1
    norm: true               # score normalization on/off
  postprocessor_sweep:
    alpha_list: [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0]  # overridden per dataset in the postprocessor
    norm_list: [false, true]
